## Define output path for run
run_path: "/p/project/hai_rnareplearn/RUNS/600k_pretraining_25epochs_undirected"

## Define initial dataset
ds_base_path: "/p/project/hai_rnareplearn/small_RFAM"
ds_names: "all"

## Separate Test/Train 
train_test_split: [0.8, 0.2]

## create k_folds (no folds: k=1)
k_folds: 1
k_fold_split: [0.8, 0.2]


gin-path: "/p/project/hai_rnareplearn/RNARepLearn/config/PreTrained_Models"

cluster: True

data_parallel: False